site_name: Embeded Summary
theme:
  name: mkdocs
  font:
    text: K2D
nav:
  - Home: index.md
  - Midterm: midterm.md
  - Chapter 9 : interrupt.md
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style.css